# Generated by Django 5.0.6 on 2024-05-20 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliothecaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenoms', models.CharField(max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.CharField(blank=True, max_length=15, null=True)),
                ('identifiant', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('codeGenre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lecteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenoms', models.CharField(max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.CharField(blank=True, max_length=15, null=True)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('auteur', models.CharField(max_length=255)),
                ('status_lecture', models.BooleanField(default=False)),
                ('note', models.IntegerField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_appli.genre')),
            ],
        ),
    ]
